name: Test PDF

on:
  pull_request:
    branches: [dev]

jobs:
  docker_changes:
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
      full_image: ${{ steps.get_image.outputs.full_image }}

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docker:
              - 'Dockerfile'
      
      - name: Determine Docker Tag
        id: get_image
        run: |
          OWNER=${{ github.repository_owner }}
          IMAGE_PATH="ghcr.io/${OWNER,,}/1-xetex-compiler"
          PR_TAG="pr-${{ github.event.pull_request.number }}"

          if [ "${{ steps.filter.outputs.docker }}" == "true" ] || docker manifest inspect ${IMAGE_PATH}:${PR_TAG} > /dev/null 2>&1; then
            echo "full_image=${IMAGE_PATH}:${PR_TAG}" >> $GITHUB_OUTPUT
          else
            echo "full_image=${IMAGE_PATH}:dev" >> $GITHUB_OUTPUT
          fi

  build_docker:
    needs: docker_changes
    if: needs.docker_changes.outputs.docker == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ needs.docker_changes.outputs.full_image }}

  build_pdf:
    needs: [docker_changes, build_docker]
    if: always() && (needs.build_docker.result == 'success' || needs.build_docker.result == 'skipped')
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.docker_changes.outputs.full_image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Compile PDF
        run: |
          make clean
          make pdf